# Generated by Django 3.0.8 on 2020-07-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='contact',
            field=models.IntegerField(default='0'),
        ),
    ]
