# Generated by Django 3.0.8 on 2020-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200720_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='contact',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
