# Generated by Django 3.0.8 on 2020-07-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('body_text', models.TextField()),
                ('date', models.CharField(max_length=12)),
                ('pic', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('site_name', models.CharField(default='-', max_length=50)),
            ],
        ),
    ]
