# Generated by Django 3.0.8 on 2020-07-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='site_name',
        ),
    ]
