# Generated by Django 3.0.8 on 2020-07-22 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200722_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 21, 8, 19, 886902)),
        ),
    ]
