# Generated by Django 3.0.8 on 2020-07-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200722_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='headline',
        ),
    ]
